title: beldmian's blog
author: beldmian
email: beldmian@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Just a backend developer blog
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: /

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Белоусов Дмитрий
  tagline: Бэкенд разработчик
  date_format: "%b %-d, %Y"
  style: black
  showNav: false
  showPicker: false

  # generate social links in footer
  social_links:
    github:  beldmian
    #linkedIn: in/thelehhman
    #rss: rss

plugins:
  - jekyll-seo-tag
